// Generated by Wrangler
// by running `wrangler types --env-interface CloudflareEnv cloudflare-env.d.ts`

// biome-ignore lint/correctness/noUnusedVariables: <explanation>
interface CloudflareEnv {
  R2_BUCKET: R2Bucket;
  NEXT_PUBLIC_R2_ACCOUNT_ID: string;
  NEXT_PUBLIC_R2_BUCKET_NAME: string;
}
